version: "3"

networks:
    daily:
        driver: bridge

services:
    mysql:
        image: "mysql:latest"
        hostname: mysql
        restart: always
        networks:
            - daily
        environment:
            - MYSQL_ROOT_PASSWORD=1
            - MYSQL_DATABASE=daily
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=1
        ports:
            - "3301:3306"
